### ISSUE TITLE
Makefile gives error on windows

### ISSUE THREAD

**Issue by ghost** [alexAubin/customMidiController#2]
It gives me the error "makefile:57: *** ARDUINODIR is not set correctly; arduino software not found.  Stop.". This is because the directory that is set doesn't work on my system.

**Comment by alexAubin** [comment]
Ugh sorry about that ... But I haven't run this thing for something like 3 or 4 years now :/

**Comment by ghost** [comment]
Is there a way I can get this working? What OS did you use to originally compile it? I'm really bad at low-level programming, and this would make it way easier to make a midi device as I don't have to do all of the hard code.

**Comment by ghost** [comment]
I compiled it in the ubuntu terminal you can get on windows and it worked without any errors.

**Comment by 4dvn** [comment]
> I compiled it in the ubuntu terminal you can get on windows and it worked without any errors.

Can you tell my how to compile it?
